export const mappedAttributes: Map<string, string> = new Map<string, string>([
  ['additionalEquipment', 'Mehr-Ausstattung'],
  ['ads', 'Inserate'],
  ['bodyType', 'Karosserie'],
  ['brand', 'Marke'],
  ['budget', 'Verfügbares Budget'],
  ['capacity', 'Hubraum'],
  ['colorAndMaterialInterior', 'Innenfarbe'],
  ['colorExterior', 'Außenfarbe'],
  ['colorExteriorManufacturer', 'Hersteller Farbbezeichnung'],
  ['condition', 'Zustand'],
  ['contactDetails.company', 'Kontaktdetails - Firma'],
  ['contactDetails.email', 'Kontaktdetails - Email'],
  ['contactDetails.freeText', 'Kontaktdetails - Freitext'],
  ['contactDetails.name', 'Kontaktdetails - Name'],
  ['contactDetails.phone', 'Kontaktdetails - Telefon'],
  ['countryOfOrigin', 'Auslieferungsland'],
  ['description', 'Detailbeschreibung'],
  ['highlights', 'Besonderheiten / Highlights'],
  ['horsePower', 'PS'],
  ['mileage', 'Laufleistung'],
  ['modelDetails', 'Modellspezifikation'],
  ['modelSeries', 'Modellreihe'],
  ['modelYear', 'Modelljahr'],
  ['mustHaves', 'Must-Haves'],
  ['noGos', 'No-Gos'],
  ['ownerName', 'Erstellt durch'],
  ['price', 'Preis in Euro'],
  ['shortDescription', 'Kurzbeschreibung'],
  ['transmission', 'Getriebe'],
  ['type', 'Typ'],
  ['updatedAt', 'Zuletzt aktualisiert'],
  ['vin', 'Fahrgestellnummer'],
  ['vision', 'Vision']
])